### ISSUE TITLE
Simplify site-header pattern

### ISSUE THREAD

**Issue by HugoGiraudel** [cjcenizal/flexbox-patterns#2]
Link: http://www.flexboxpatterns.com/site-header.

## Proposal

```html
<div class="siteHeader">
  <div class="siteHeader__item siteHeaderLogo">
    <div class="fa fa-inbox"></div>
  </div>
  <div class="siteHeader__item siteHeaderButton is-site-header-item-selected">Inbox</div>
  <div class="siteHeader__item siteHeaderButton">Sent</div>
  <div class="siteHeader__item siteHeaderButton">Trash</div>
  <div class="siteHeader__item siteHeaderButton">Settings</div>
</div>
```

## CSS

```css
.siteHeader {
  display: flex;
  padding: 10px;
  background-color: #56727C;
}

    /* ... */
    .siteHeader__item:last-child {
      margin-left: auto;
    }
```

No need for sub-sections anymore. :)

Cheers.
